# Generated by Django 4.2.4 on 2023-08-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_no_of_guests_alter_menu_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_guests',
            new_name='guest_num',
        ),
    ]
